export const NotificationDispatchedState = {
    NOT_DISPATCHED: "NOT_DISPATCHED",
    FIRST_RETRY: "FIRST_RETRY",
    SECOND_RETRY: "SECOND_RETRY",
    THIRD_RETRY: "THIRD_RETRY",
    DISPATCHED: "DISPATCHED",
    DELETED: "DELETED",
    FAILED: "FAILED"
} as const;
export type NotificationDispatchedState = (typeof NotificationDispatchedState)[keyof typeof NotificationDispatchedState];
export const NotificationType = {
    BULLETIN_EMAIL: "BULLETIN_EMAIL",
    QUORUM_NOT_REACHED_EMAIL: "QUORUM_NOT_REACHED_EMAIL",
    TIMEEND_EMAIL: "TIMEEND_EMAIL"
} as const;
export type NotificationType = (typeof NotificationType)[keyof typeof NotificationType];
export const DAOHandlerEnum = {
    AAVE_V2_MAINNET: "AAVE_V2_MAINNET",
    COMPOUND_MAINNET: "COMPOUND_MAINNET",
    UNISWAP_MAINNET: "UNISWAP_MAINNET",
    ENS_MAINNET: "ENS_MAINNET",
    GITCOIN_MAINNET: "GITCOIN_MAINNET",
    GITCOIN_V2_MAINNET: "GITCOIN_V2_MAINNET",
    HOP_MAINNET: "HOP_MAINNET",
    DYDX_MAINNET: "DYDX_MAINNET",
    INTEREST_PROTOCOL_MAINNET: "INTEREST_PROTOCOL_MAINNET",
    ZEROX_PROTOCOL_MAINNET: "ZEROX_PROTOCOL_MAINNET",
    FRAX_ALPHA_MAINNET: "FRAX_ALPHA_MAINNET",
    FRAX_OMEGA_MAINNET: "FRAX_OMEGA_MAINNET",
    NOUNS_PROPOSALS_MAINNET: "NOUNS_PROPOSALS_MAINNET",
    OP_OPTIMISM: "OP_OPTIMISM",
    ARB_CORE_ARBITRUM: "ARB_CORE_ARBITRUM",
    ARB_TREASURY_ARBITRUM: "ARB_TREASURY_ARBITRUM",
    MAKER_EXECUTIVE_MAINNET: "MAKER_EXECUTIVE_MAINNET",
    MAKER_POLL_MAINNET: "MAKER_POLL_MAINNET",
    MAKER_POLL_ARBITRUM: "MAKER_POLL_ARBITRUM",
    AAVE_V3_MAINNET: "AAVE_V3_MAINNET",
    AAVE_V3_POLYGON_POS: "AAVE_V3_POLYGON_POS",
    AAVE_V3_AVALANCHE: "AAVE_V3_AVALANCHE",
    SNAPSHOT: "SNAPSHOT"
} as const;
export type DAOHandlerEnum = (typeof DAOHandlerEnum)[keyof typeof DAOHandlerEnum];
export const ProposalStateEnum = {
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    CANCELED: "CANCELED",
    DEFEATED: "DEFEATED",
    SUCCEEDED: "SUCCEEDED",
    QUEUED: "QUEUED",
    EXPIRED: "EXPIRED",
    EXECUTED: "EXECUTED",
    HIDDEN: "HIDDEN",
    UNKNOWN: "UNKNOWN"
} as const;
export type ProposalStateEnum = (typeof ProposalStateEnum)[keyof typeof ProposalStateEnum];
