const config = {
  darkMode: ['class'],
  content: ['./app/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Fira Sans', 'sans-serif'],
        mono: ['Fira Mono', 'monospace'],
        condensed: ['Fira Sans Condensed', 'sans-serif'],
      },
      colors: {
        for: {
          400: 'var(--for-400)',
          600: 'var(--for-600)',
        },
        abstain: {
          400: 'var(--abstain-400)',
          600: 'var(--abstain-600)',
        },
        against: {
          400: 'var(--against-400)',
          600: 'var(--against-600)',
        },
        neutral: {
          50: 'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          350: 'var(--neutral-350)',
          400: 'var(--neutral-400)',
          450: 'var(--neutral-450)',
          500: 'var(--neutral-500)',
          550: 'var(--neutral-550)',
          600: 'var(--neutral-600)',
          650: 'var(--neutral-650)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          950: 'var(--neutral-950)',
        },
        brand: {
          accent: 'var(--brand-accent)',
        },
      },
      typography: () => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': 'var(--color-neutral-800)',
            '--tw-prose-headings': 'var(--color-neutral-900)',
            '--tw-prose-lead': 'var(--color-neutral-700)',
            '--tw-prose-links': 'var(--color-neutral-900)',
            '--tw-prose-bold': 'var(--color-neutral-900)',
            '--tw-prose-counters': 'var(--color-neutral-600)',
            '--tw-prose-bullets': 'var(--color-neutral-400)',
            '--tw-prose-hr': 'var(--color-neutral-300)',
            '--tw-prose-quotes': 'var(--color-neutral-900)',
            '--tw-prose-quote-borders': 'var(--color-neutral-300)',
            '--tw-prose-captions': 'var(--color-neutral-700)',
            '--tw-prose-code': 'var(--color-neutral-900)',
            '--tw-prose-pre-code': 'var(--color-neutral-100)',
            '--tw-prose-pre-bg': 'var(--color-neutral-900)',
            '--tw-prose-th-borders': 'var(--color-neutral-300)',
            '--tw-prose-td-borders': 'var(--color-neutral-200)',
            '--tw-prose-invert-body': 'var(--color-neutral-200)',
            '--tw-prose-invert-headings': 'var(--color-white)',
            '--tw-prose-invert-lead': 'var(--color-neutral-300)',
            '--tw-prose-invert-links': 'var(--color-white)',
            '--tw-prose-invert-bold': 'var(--color-white)',
            '--tw-prose-invert-counters': 'var(--color-neutral-400)',
            '--tw-prose-invert-bullets': 'var(--color-neutral-600)',
            '--tw-prose-invert-hr': 'var(--color-neutral-700)',
            '--tw-prose-invert-quotes': 'var(--color-neutral-100)',
            '--tw-prose-invert-quote-borders': 'var(--color-neutral-700)',
            '--tw-prose-invert-captions': 'var(--color-neutral-400)',
            '--tw-prose-invert-code': 'var(--color-white)',
            '--tw-prose-invert-pre-code': 'var(--color-neutral-300)',
            '--tw-prose-invert-pre-bg': 'rgb(0 0 0 / 50%)',
            '--tw-prose-invert-th-borders': 'var(--color-neutral-600)',
            '--tw-prose-invert-td-borders': 'var(--color-neutral-700)',
          },
        },
      }),
    },
  },
  plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
};

export default config;
