services:
  ch-server:
    image: clickhouse/clickhouse-server:latest
    container_name: ch-server
    ports:
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./clickhouse/ddl:/docker-entrypoint-initdb.d
      - ./clickhouse/config/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/config/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse-logs:/var/log/clickhouse-server
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=otel
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    networks:
      - observe-network
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 10s
      retries: 5

  otelcol:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-col
    hostname: otel-col
    restart: unless-stopped
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ./otel/otelcol-config.yml:/etc/otelcol-config.yml
    environment:
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    networks:
      - observe-network
    depends_on:
      ch-server:
        condition: service_healthy

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
    environment:
      - NGINX_BEARER_TOKEN=${NGINX_BEARER_TOKEN}
      - TOKEN=${NGINX_BEARER_TOKEN}
    command: /bin/bash -c "envsubst '$$TOKEN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - observe-network
    depends_on:
      - otelcol

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "8080:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      # Add these environment variables
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=5s
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_DASHBOARDS=/var/lib/grafana/dashboards
      # Enable saving dashboards to the file system
      - GF_DASHBOARDS_JSON_ENABLED=true
      - GF_DASHBOARDS_JSON_PATH=/var/lib/grafana/dashboards
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      # Ensure the dashboards directory has read-write permissions
      - ./grafana/dashboards:/var/lib/grafana/dashboards:rw
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - observe-network
    depends_on:
      - ch-server

networks:
  observe-network:

volumes:
  mongodb-data:
  clickhouse-data:
  grafana-storage:
