services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    hostname: otel-collector
    restart: unless-stopped
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otel-collector-config.yml
      - ./storage/otel-collector/logs:/var/log/otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    networks:
      - observe-network
    depends_on:
      - loki
      - tempo
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./storage/grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_DISABLE_INITIAL_ADMIN_PASSWORD_HINT=true
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=postgres
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=grafana
      - GF_DATABASE_PASSWORD=your_secure_db_password
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app
    networks:
      - observe-network
    depends_on:
      - postgres
      - prometheus
      - loki
      - tempo
      - pyroscope

  pmm-server:
    image: percona/pmm-server:latest
    container_name: pmm-server
    hostname: pmm-server
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PMM_DEBUG=0
      - PMM_RETENTION=30
    volumes:
      - ./storage/pmm-server:/srv
    networks:
      - observe-network

  pmm-client:
    image: percona/pmm-client:latest
    container_name: pmm-client
    hostname: pmm-client
    environment:
      - PMM_AGENT_SERVER_ADDRESS=pmm-server:443
      - PMM_AGENT_SERVER_INSECURE_TLS=1
      - PMM_AGENT_SETUP=1
      - PMM_AGENT_CONFIG_FILE=/usr/local/percona/pmm2/config/pmm-agent.yaml
      - PMM_AGENT_SERVER_USERNAME=admin
      - PMM_AGENT_SERVER_PASSWORD=admin
      - PMM_AGENT_PATHS_EXPORTERS_BASE_PATH=/usr/local/percona/pmm2
      - PMM_AGENT_SETUP_NODE_NAME=main-db
      - PMM_AGENT_SETUP_FORCE=1
      - PMM_AGENT_SETUP_METRICS_MODE=push
      # Auto-configuration for main database
      - MAIN_DATABASE_URL=${DATABASE_URL}
      - PMM_AGENT_SETUP_POSTGRESQL_MAIN_DSN=${DATABASE_URL}
      - PMM_AGENT_SETUP_POSTGRESQL_MAIN_SERVICE_NAME=main-db
      - PMM_AGENT_SETUP_POSTGRESQL_MAIN_ENVIRONMENT=production
      - PMM_AGENT_SETUP_POSTGRESQL_MAIN_CLUSTER=main-cluster
      # Auto-configuration for web database
      - WEB_DATABASE_URL=${WEB_DATABASE_URL}
      - PMM_AGENT_SETUP_POSTGRESQL_WEB_DSN=${WEB_DATABASE_URL}
      - PMM_AGENT_SETUP_POSTGRESQL_WEB_SERVICE_NAME=web-db
      - PMM_AGENT_SETUP_POSTGRESQL_WEB_ENVIRONMENT=production
      - PMM_AGENT_SETUP_POSTGRESQL_WEB_CLUSTER=web-cluster
    volumes:
      - ./storage/pmm-client:/usr/local/percona/pmm2
      # Add setup script
      - ./pmm-client/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    networks:
      - observe-network
    depends_on:
      - pmm-server

  postgres:
    image: postgres:13
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: your_secure_db_password
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    networks:
      - observe-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./storage/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    networks:
      - observe-network
    depends_on:
      - postgres

  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope
    hostname: pyroscope
    restart: unless-stopped
    ports:
      - "4040:4040"
    volumes:
      - ./storage/pyroscope:/var/lib/pyroscope
    environment:
      - PYROSCOPE_STORAGE_PATH=/var/lib/pyroscope
      - PYROSCOPE_LOG_LEVEL=debug
      # Memory configuration
      - PYROSCOPE_HEAP_SIZE=4096 # 4GB
      - PYROSCOPE_MEMORY_SPIKE_LIMIT=2048 # 2GB
      # Ingestion limits
      - PYROSCOPE_INGESTION_MAX_PAYLOAD_SIZE=250000000
      # Retention settings
      - PYROSCOPE_RETENTION=24h
      # Query limits
      - PYROSCOPE_QUERY_MAX_CONCURRENT=20
      - PYROSCOPE_QUERY_TIMEOUT=5m
    networks:
      - observe-network
    depends_on:
      - prometheus

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    hostname: tempo
    restart: unless-stopped
    volumes:
      - ./storage/tempo:/var/tempo
      - ./tempo/tempo-config.yml:/etc/tempo/config.yml
    command: "-config.file=/etc/tempo/config.yml"
    networks:
      - observe-network
    depends_on:
      - loki

  loki:
    image: grafana/loki:latest
    container_name: loki
    hostname: loki
    restart: unless-stopped
    volumes:
      - ./storage/loki:/var/loki
      - ./loki/loki-config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - observe-network
    depends_on:
      - prometheus

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    hostname: promtail
    restart: unless-stopped
    volumes:
      - ./loki/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - observe-network
    depends_on:
      - loki

networks:
  observe-network:
    name: observe-network
