#![allow(clippy::all, dead_code, unused)]
// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
//
// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer.
// Any manual changes to this file will be overwritten.
pub mod arb_token;
mod arb_token_abi_gen;
pub mod arbitrum_core_governor;
pub(crate) mod arbitrum_core_governor_abi_gen;
pub mod arbitrum_sc_nominations;
pub(crate) mod arbitrum_sc_nominations_abi_gen;
pub mod arbitrum_treasury_governor;
pub(crate) mod arbitrum_treasury_governor_abi_gen;
pub mod uni_governor;
pub(crate) mod uni_governor_abi_gen;
pub mod uni_token;
mod uni_token_abi_gen;
