#![allow(dead_code, unused)]

pub mod arb_token;
/// THIS IS A GENERATED FILE. DO NOT MODIFY MANUALLY.
///
/// This file was auto generated by rindexer - https://github.com/joshstevens19/rindexer
/// Any manual changes to this file will be overwritten.
mod arb_token_abi_gen;
pub mod arbitrum_core_governor;
mod arbitrum_core_governor_abi_gen;
pub mod arbitrum_sc_nominations;
mod arbitrum_sc_nominations_abi_gen;
pub mod arbitrum_treasury_governor;
mod arbitrum_treasury_governor_abi_gen;
pub mod uni_token;
mod uni_token_abi_gen;
