[package]
name = "rindexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
dotenv = { workspace = true }
ethers = { workspace = true, features = ["rustls", "openssl"] }
once_cell = { workspace = true }
proposalsapp-db = { path = "../../libs/rust/db" }
rindexer = { workspace = true }
sea-orm = { workspace = true, features = [
    "sqlx-mysql",
    "runtime-tokio-rustls",
    "macros",
    "with-chrono",
    "with-json",
    "with-bigdecimal",
    "with-uuid",
] }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }

[[bin]]
name = "rindexer"
path = "src/main.rs"
