volumes:
  postgres_data:
    driver: local

services:
  redis:
    image: redis
    container_name: rindexer-redis
    logging:
      driver: none
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]

  postgresql:
    image: postgres:16
    shm_size: 1g
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5440:5432
    env_file:
      - ./.env
