all:
  children:
    consul_servers:
      hosts:
        consul-nomad-fsn-01: null
        consul-nomad-sib-01: null
        consul-nomad-sib-03: null
    github_runners:
      hosts:
        github-runner-fsn-01: null
        github-runner-sib-01: null
        github-runner-sib-03: null
    lxc_containers:
      hosts:
        apps-fsn-01:
          ansible_host: apps-fsn-01
          container_id: 5303
          datacenter: dc3
          proxmox_node: fsn-01
          tailscale_ip: 100.83.36.94
        apps-sib-01:
          ansible_host: apps-sib-01
          container_id: 5103
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.70.165.7
        apps-sib-03:
          ansible_host: apps-sib-03
          container_id: 5203
          datacenter: dc2
          proxmox_node: sib-03
          tailscale_ip: 100.111.87.68
        consul-nomad-fsn-01:
          ansible_host: consul-nomad-fsn-01
          container_id: 5301
          datacenter: dc3
          proxmox_node: fsn-01
          tailscale_ip: 100.69.128.83
        consul-nomad-sib-01:
          ansible_host: consul-nomad-sib-01
          container_id: 5101
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.82.212.113
        consul-nomad-sib-03:
          ansible_host: consul-nomad-sib-03
          container_id: 5201
          datacenter: dc2
          proxmox_node: sib-03
          tailscale_ip: 100.64.1.6
        db-fsn-01:
          ansible_host: db-fsn-01
          container_id: 5302
          datacenter: dc3
          postgres_role: standby
          proxmox_node: fsn-01
          tailscale_ip: 100.123.136.2
        db-sib-01:
          ansible_host: db-sib-01
          container_id: 5102
          datacenter: dc1
          postgres_role: primary
          proxmox_node: sib-01
          tailscale_ip: 100.118.163.74
        db-sib-03:
          ansible_host: db-sib-03
          container_id: 5202
          datacenter: dc2
          postgres_role: standby
          proxmox_node: sib-03
          tailscale_ip: 100.89.52.125
        github-runner-fsn-01:
          ansible_host: github-runner-fsn-01
          container_id: 5304
          datacenter: dc3
          proxmox_node: fsn-01
          tailscale_ip: 100.74.161.119
        github-runner-sib-01:
          ansible_host: github-runner-sib-01
          container_id: 5104
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.84.196.37
        github-runner-sib-03:
          ansible_host: github-runner-sib-03
          container_id: 5204
          datacenter: dc2
          proxmox_node: sib-03
          tailscale_ip: 100.122.138.116
    nomad_clients:
      hosts:
        apps-fsn-01: null
        apps-sib-01: null
        apps-sib-03: null
    nomad_servers:
      hosts:
        consul-nomad-fsn-01: null
        consul-nomad-sib-01: null
        consul-nomad-sib-03: null
    postgres_nodes:
      hosts:
        db-fsn-01: null
        db-sib-01: null
        db-sib-03: null
    proxmox_nodes:
      hosts:
        fsn-01:
          ansible_host: 100.67.115.98
          datacenter: dc3
          location: falkenstein
        sib-01:
          ansible_host: 100.66.59.61
          datacenter: dc1
          location: sibiu
        sib-03:
          ansible_host: 100.127.112.5
          datacenter: dc2
          location: sibiu
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
