all:
  children:
    consul_servers:
      hosts:
        consul-nomad-sib-01: null
        consul-nomad-sib-02: null
        consul-nomad-sib-03: null
    github_runners:
      hosts:
        github-runner-sib-01: null
        github-runner-sib-02: null
        github-runner-sib-03: null
    gpu_hosts:
      hosts:
        sib-03: null
    lxc_containers:
      hosts:
        apps-sib-01:
          ansible_host: apps-sib-01
          container_id: 5103
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.98.78.74
        apps-sib-02:
          ansible_host: apps-sib-02
          container_id: 5203
          datacenter: dc2
          proxmox_node: sib-02
          tailscale_ip: 100.108.36.54
        apps-sib-03:
          ansible_host: apps-sib-03
          container_id: 5303
          datacenter: dc3
          proxmox_node: sib-03
          tailscale_ip: 100.102.116.15
        consul-nomad-sib-01:
          ansible_host: consul-nomad-sib-01
          container_id: 5101
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.107.55.91
        consul-nomad-sib-02:
          ansible_host: consul-nomad-sib-02
          container_id: 5201
          datacenter: dc2
          proxmox_node: sib-02
          tailscale_ip: 100.85.78.68
        consul-nomad-sib-03:
          ansible_host: consul-nomad-sib-03
          container_id: 5301
          datacenter: dc3
          proxmox_node: sib-03
          tailscale_ip: 100.85.28.51
        db-sib-01:
          ansible_host: db-sib-01
          container_id: 5102
          datacenter: dc1
          postgres_role: primary
          proxmox_node: sib-01
          tailscale_ip: 100.79.59.84
        db-sib-02:
          ansible_host: db-sib-02
          container_id: 5202
          datacenter: dc2
          postgres_role: standby
          proxmox_node: sib-02
          tailscale_ip: 100.111.108.53
        db-sib-03:
          ansible_host: db-sib-03
          container_id: 5302
          datacenter: dc3
          postgres_role: standby
          proxmox_node: sib-03
          tailscale_ip: 100.93.140.2
        github-runner-sib-01:
          ansible_host: github-runner-sib-01
          container_id: 5104
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.65.13.46
        github-runner-sib-02:
          ansible_host: github-runner-sib-02
          container_id: 5204
          datacenter: dc2
          proxmox_node: sib-02
          tailscale_ip: 100.97.211.121
        github-runner-sib-03:
          ansible_host: github-runner-sib-03
          container_id: 5304
          datacenter: dc3
          proxmox_node: sib-03
          tailscale_ip: 100.119.235.83
        pgbackweb-sib-01:
          ansible_host: pgbackweb-sib-01
          container_id: 5107
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.69.13.22
        redis-sib-01:
          ansible_host: redis-sib-01
          container_id: 5105
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.126.149.11
        redis-sib-02:
          ansible_host: redis-sib-02
          container_id: 5205
          datacenter: dc2
          proxmox_node: sib-02
          tailscale_ip: 100.70.81.52
        redis-sib-03:
          ansible_host: redis-sib-03
          container_id: 5305
          datacenter: dc3
          proxmox_node: sib-03
          tailscale_ip: 100.83.65.32
    nomad_clients:
      hosts:
        apps-sib-01: null
        apps-sib-02: null
        apps-sib-03: null
    nomad_servers:
      hosts:
        consul-nomad-sib-01: null
        consul-nomad-sib-02: null
        consul-nomad-sib-03: null
    pgbackweb:
      hosts:
        pgbackweb-sib-01: null
    postgres_nodes:
      hosts:
        db-sib-01: null
        db-sib-02: null
        db-sib-03: null
    proxmox_nodes:
      hosts:
        sib-01:
          ansible_host: 100.66.59.61
          datacenter: dc1
          location: sibiu
        sib-02:
          ansible_host: 100.115.192.22
          datacenter: dc2
          location: sibiu
        sib-03:
          ansible_host: 100.127.112.5
          datacenter: dc3
          location: sibiu
    redis_nodes:
      hosts:
        redis-sib-01: null
        redis-sib-02: null
        redis-sib-03: null
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
