all:
  children:
    consul_servers:
      hosts:
        consul-nomad-fsn-01: null
        consul-nomad-sib-01: null
        consul-nomad-sib-03: null
    lxc_containers:
      hosts:
        apps-fsn-01:
          ansible_host: apps-fsn-01
          container_id: 581
          datacenter: dc3
          proxmox_node: fsn-01
          tailscale_ip: 100.101.38.93
        apps-sib-01:
          ansible_host: apps-sib-01
          container_id: 521
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.99.188.32
        apps-sib-03:
          ansible_host: apps-sib-03
          container_id: 551
          datacenter: dc2
          proxmox_node: sib-03
          tailscale_ip: 100.116.181.44
        consul-nomad-fsn-01:
          ansible_host: consul-nomad-fsn-01
          container_id: 561
          datacenter: dc3
          proxmox_node: fsn-01
          tailscale_ip: 100.102.53.60
        consul-nomad-sib-01:
          ansible_host: consul-nomad-sib-01
          container_id: 501
          datacenter: dc1
          proxmox_node: sib-01
          tailscale_ip: 100.116.189.123
        consul-nomad-sib-03:
          ansible_host: consul-nomad-sib-03
          container_id: 531
          datacenter: dc2
          proxmox_node: sib-03
          tailscale_ip: 100.101.227.90
        db-fsn-01:
          ansible_host: db-fsn-01
          container_id: 571
          datacenter: dc3
          postgres_role: standby
          proxmox_node: fsn-01
          tailscale_ip: 100.104.108.6
        db-sib-01:
          ansible_host: db-sib-01
          container_id: 511
          datacenter: dc1
          postgres_role: primary
          proxmox_node: sib-01
          tailscale_ip: 100.113.161.123
        db-sib-03:
          ansible_host: db-sib-03
          container_id: 541
          datacenter: dc2
          postgres_role: standby
          proxmox_node: sib-03
          tailscale_ip: 100.88.2.28
    nomad_clients:
      hosts:
        apps-fsn-01: null
        apps-sib-01: null
        apps-sib-03: null
    nomad_servers:
      hosts:
        consul-nomad-fsn-01: null
        consul-nomad-sib-01: null
        consul-nomad-sib-03: null
    postgres_nodes:
      hosts:
        db-fsn-01: null
        db-sib-01: null
        db-sib-03: null
    proxmox_nodes:
      hosts:
        fsn-01:
          ansible_host: 100.67.115.98
          datacenter: dc3
          location: falkenstein
        sib-01:
          ansible_host: 100.66.59.61
          datacenter: dc1
          location: sibiu
        sib-03:
          ansible_host: 100.127.112.5
          datacenter: dc2
          location: sibiu
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: root
