---
- name: Setup Consul KV values for Cloudflared
  hosts: consul_servers
  become: true
  vars:
    consul_kv_values:
      - key: "cloudflared/tunnel_token"
        value: "{{ vault_cloudflare_tunnel_token }}"

  tasks:
    - name: Ensure Consul is available
      wait_for:
        port: 8500
        host: localhost
        timeout: 60

    - name: Get local Consul datacenter info
      uri:
        url: "http://localhost:8500/v1/agent/self"
        method: GET
      register: consul_info

    - name: Set datacenter variable
      set_fact:
        current_datacenter: "{{ consul_info.json.Config.Datacenter }}"

    - name: Store Cloudflare tunnel token in Consul KV
      uri:
        url: "http://localhost:8500/v1/kv/{{ item.key }}"
        method: PUT
        body: "{{ item.value }}"
      loop: "{{ consul_kv_values }}"
      loop_control:
        label: "{{ item.key }} in {{ current_datacenter }}"
      no_log: true # Don't log the sensitive token

    - name: Display setup information
      debug:
        msg: |
          ========================================
          Cloudflared Setup Complete for {{ current_datacenter }}
          ========================================

          The Cloudflare tunnel token has been stored in Consul KV.

          Run this playbook on all consul servers to replicate
          the configuration across all datacenters.
          ========================================
      run_once: true

- name: Display deployment instructions
  hosts: localhost
  connection: local
  tasks:
    - name: Show deployment instructions
      debug:
        msg: |
          ========================================
          Cloudflared Setup Complete
          ========================================

          To deploy Cloudflared:
          1. Ensure this playbook has been run on all consul servers
          2. Run: nomad job run applications/cloudflared/cloudflared.nomad

          The Cloudflared tunnel will:
          - Establish secure connection to Cloudflare's edge
          - Enable Zero Trust access to internal services
          - Provide metrics on port 2000
          - Automatically migrate to another DC if current node fails

          To verify the deployment:
          - Check Nomad: nomad job status cloudflared
          - Check metrics: curl http://<node>:2000/metrics
          - Check Cloudflare dashboard for tunnel status

          Note: The tunnel token contains all necessary configuration
          including the tunnel ID and credentials.
          ========================================
