//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::{
    dao::Entity as Dao, dao_discourse::Entity as DaoDiscourse, dao_indexer::Entity as DaoIndexer,
    delegation::Entity as Delegation, discourse_category::Entity as DiscourseCategory,
    discourse_post::Entity as DiscoursePost,
    discourse_post_revision::Entity as DiscoursePostRevision,
    discourse_topic::Entity as DiscourseTopic, discourse_user::Entity as DiscourseUser,
    email_verification::Entity as EmailVerification, job_queue::Entity as JobQueue,
    kysely_migration::Entity as KyselyMigration,
    kysely_migration_lock::Entity as KyselyMigrationLock, notification::Entity as Notification,
    proposal::Entity as Proposal, proposal_group::Entity as ProposalGroup,
    subscription::Entity as Subscription, user::Entity as User,
    user_push_notification_subscription::Entity as UserPushNotificationSubscription,
    user_session::Entity as UserSession, user_settings::Entity as UserSettings,
    user_to_voter::Entity as UserToVoter, vote::Entity as Vote, voter::Entity as Voter,
    voting_power::Entity as VotingPower,
};
