//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::{
    countdown_cache::Entity as CountdownCache, dao::Entity as Dao,
    dao_handler::Entity as DaoHandler, dao_settings::Entity as DaoSettings,
    email_verification::Entity as EmailVerification, kysely_migration::Entity as KyselyMigration,
    kysely_migration_lock::Entity as KyselyMigrationLock, notification::Entity as Notification,
    proposal::Entity as Proposal, subscription::Entity as Subscription, user::Entity as User,
    user_push_notification_subscription::Entity as UserPushNotificationSubscription,
    user_session::Entity as UserSession, user_settings::Entity as UserSettings,
    user_to_voter::Entity as UserToVoter, vote::Entity as Vote, voter::Entity as Voter,
};
