//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use super::sea_orm_active_enums::ProposalStateEnum;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "proposal"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub index_created: i32,
    pub votes_fetched: bool,
    pub votes_refresh_speed: i32,
    pub votes_index: i32,
    pub external_id: String,
    pub name: String,
    pub body: String,
    pub url: String,
    pub discussion_url: String,
    pub choices: Json,
    pub scores: Json,
    pub scores_total: f64,
    pub quorum: f64,
    pub proposal_state: ProposalStateEnum,
    pub flagged: bool,
    pub block_created: Option<i32>,
    pub time_created: Option<DateTime>,
    pub time_start: DateTime,
    pub time_end: DateTime,
    pub dao_handler_id: Uuid,
    pub dao_id: Uuid,
    pub scores_quorum: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    IndexCreated,
    VotesFetched,
    VotesRefreshSpeed,
    VotesIndex,
    ExternalId,
    Name,
    Body,
    Url,
    DiscussionUrl,
    Choices,
    Scores,
    ScoresTotal,
    Quorum,
    ProposalState,
    Flagged,
    BlockCreated,
    TimeCreated,
    TimeStart,
    TimeEnd,
    DaoHandlerId,
    DaoId,
    ScoresQuorum,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Dao,
    DaoHandler,
    Notification,
    Vote,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::IndexCreated => ColumnType::Integer.def(),
            Self::VotesFetched => ColumnType::Boolean.def(),
            Self::VotesRefreshSpeed => ColumnType::Integer.def(),
            Self::VotesIndex => ColumnType::Integer.def(),
            Self::ExternalId => ColumnType::Text.def(),
            Self::Name => ColumnType::Text.def(),
            Self::Body => ColumnType::Text.def(),
            Self::Url => ColumnType::Text.def(),
            Self::DiscussionUrl => ColumnType::Text.def(),
            Self::Choices => ColumnType::Json.def(),
            Self::Scores => ColumnType::Json.def(),
            Self::ScoresTotal => ColumnType::Double.def(),
            Self::Quorum => ColumnType::Double.def(),
            Self::ProposalState => ProposalStateEnum::db_type().def(),
            Self::Flagged => ColumnType::Boolean.def(),
            Self::BlockCreated => ColumnType::Integer.def().null(),
            Self::TimeCreated => ColumnType::DateTime.def().null(),
            Self::TimeStart => ColumnType::DateTime.def(),
            Self::TimeEnd => ColumnType::DateTime.def(),
            Self::DaoHandlerId => ColumnType::Uuid.def(),
            Self::DaoId => ColumnType::Uuid.def(),
            Self::ScoresQuorum => ColumnType::Double.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Dao => Entity::belongs_to(super::dao::Entity)
                .from(Column::DaoId)
                .to(super::dao::Column::Id)
                .into(),
            Self::DaoHandler => Entity::belongs_to(super::dao_handler::Entity)
                .from(Column::DaoHandlerId)
                .to(super::dao_handler::Column::Id)
                .into(),
            Self::Notification => Entity::has_many(super::notification::Entity).into(),
            Self::Vote => Entity::has_many(super::vote::Entity).into(),
        }
    }
}

impl Related<super::dao::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dao.def()
    }
}

impl Related<super::dao_handler::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DaoHandler.def()
    }
}

impl Related<super::notification::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notification.def()
    }
}

impl Related<super::vote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vote.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
