---
- name: Setup Consul KV values for eRPC in all datacenters
  hosts: consul_servers
  become: true
  vars:
    consul_kv_values:
      # Hypersync node URLs (per chain)
      - key: "erpc/hypersync/ethereum"
        value: "{{ vault_erpc_hypersync_ethereum_url }}"
      - key: "erpc/hypersync/arbitrum"
        value: "{{ vault_erpc_hypersync_arbitrum_url }}"
      - key: "erpc/hypersync/optimism"
        value: "{{ vault_erpc_hypersync_optimism_url }}"
      - key: "erpc/hypersync/polygon"
        value: "{{ vault_erpc_hypersync_polygon_url }}"
      - key: "erpc/hypersync/avalanche"
        value: "{{ vault_erpc_hypersync_avalanche_url }}"
      
      # Full node URLs (per chain)
      - key: "erpc/full/ethereum"
        value: "{{ vault_erpc_full_ethereum_url }}"
      - key: "erpc/full/arbitrum"
        value: "{{ vault_erpc_full_arbitrum_url }}"
      - key: "erpc/full/optimism"
        value: "{{ vault_erpc_full_optimism_url }}"
      - key: "erpc/full/polygon"
        value: "{{ vault_erpc_full_polygon_url }}"
      - key: "erpc/full/avalanche"
        value: "{{ vault_erpc_full_avalanche_url }}"

  tasks:
    - name: Ensure Consul is available
      wait_for:
        port: 8500
        host: localhost
        timeout: 60

    - name: Get local Consul datacenter info
      uri:
        url: "http://localhost:8500/v1/agent/self"
        method: GET
      register: consul_info

    - name: Set datacenter variable
      set_fact:
        current_datacenter: "{{ consul_info.json.Config.Datacenter }}"

    - name: Store values in local datacenter's Consul KV
      uri:
        url: "http://localhost:8500/v1/kv/{{ item.key }}"
        method: PUT
        body: "{{ item.value }}"
      loop: "{{ consul_kv_values }}"
      loop_control:
        label: "{{ item.key }} in {{ current_datacenter }}"
      no_log: true # Don't log sensitive values

    - name: Display setup completion
      debug:
        msg: "Consul KV setup complete for eRPC in {{ current_datacenter }}"
      run_once: true