use seaorm::sea_orm_active_enums::DaoHandlerEnumV2;
use serde_json::json;

use crate::{DaoSeedData, HandlerData, SettingsData};

pub fn seed_data() -> Vec<DaoSeedData> {
    vec![
        DaoSeedData {
            name: "Aave".to_string(),
            slug: "aave".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/aave".to_string(),
                background_color: "#a5a9c6".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/aave.eth".to_string(),
                    decoder: json!({"snapshot_space": "aave.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::AaveV2Mainnet,
                    governance_portal: "https://app.aave.com/governance".to_string(),
                    decoder: json!({
                        "address": "0xEC568fffba86c094cf06b22134B23074DFE2252c",
                        "proposalUrl": "https://app.aave.com/governance/proposal/?proposalId=",
                    }),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::AaveV3Mainnet,
                    governance_portal: "https://app.aave.com/governance".to_string(),
                    decoder: json!({
                        "address": "0x9AEE0B04504CeF83A65AC3f0e838D0593BCb2BC7",
                        "voting_machine": "0x617332a777780F546261247F621051d0b98975Eb",
                        "proposalUrl": "https://app.aave.com/governance/v3/proposal/?proposalId=",
                    }),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::AaveV3PolygonPos,
                    governance_portal: "https://app.aave.com/governance".to_string(),
                    decoder: json!({
                        "voting_machine": "0xc8a2ADC4261c6b669CdFf69E717E77C9cFeB420d",
                        "proposalUrl": "https://app.aave.com/governance/v3/proposal/?proposalId=",
                    }),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::AaveV3Avalanche,
                    governance_portal: "https://app.aave.com/governance".to_string(),
                    decoder: json!({
                        "voting_machine": "0x9b6f5ef589A3DD08670Dd146C11C4Fb33E04494F",
                        "proposalUrl": "https://app.aave.com/governance/v3/proposal/?proposalId=",
                    }),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "Compound".to_string(),
            slug: "compound".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/compound".to_string(),
                background_color: "#00573e".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/comp-vote.eth".to_string(),
                    decoder: json!({"snapshot_space": "comp-vote.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::CompoundMainnet,
                    governance_portal: "https://compound.finance/governance".to_string(),
                    decoder: json!({"proposalUrl": "https://compound.finance/governance/proposals/", "address":"0xc0Da02939E1441F497fd74F78cE7Decb17B66529"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "dYdX".to_string(),
            slug: "dydx".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/dYdX".to_string(),
                background_color: "#51515a".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/dydxgov.eth".to_string(),
                    decoder: json!({"snapshot_space": "dydxgov.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::DydxMainnet,
                    governance_portal: "https://dydx.community/dashboard".to_string(),
                    decoder: json!({"address": "0x7E9B1672616FF6D6629Ef2879419aaE79A9018D2", "proposalUrl": "https://dydx.community/dashboard/proposal/",}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "ENS".to_string(),
            slug: "ens".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/ens".to_string(),
                background_color: "#6daef6".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/ens.eth".to_string(),
                    decoder: json!({"snapshot_space": "ens.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::EnsMainnet,
                    governance_portal: "https://www.tally.xyz/gov/ens".to_string(),
                    decoder: json!({"address": "0x323A76393544d5ecca80cd6ef2A560C6a395b7E3", "proposalUrl": "https://www.tally.xyz/gov/ens/proposal/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "Gitcoin".to_string(),
            slug: "gitcoin".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/gitcoin".to_string(),
                background_color: "#05d4a2".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/gitcoindao.eth".to_string(),
                    decoder: json!({"snapshot_space": "gitcoindao.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::GitcoinMainnet,
                    governance_portal: "https://www.tally.xyz/gov/gitcoin".to_string(),
                    decoder: json!({"address": "0xDbD27635A534A3d3169Ef0498beB56Fb9c937489", "proposalUrl": "https://www.tally.xyz/gov/gitcoin/proposal/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::GitcoinV2Mainnet,
                    governance_portal: "https://www.tally.xyz/gov/gitcoin".to_string(),
                    decoder: json!({"address": "0x9D4C63565D5618310271bF3F3c01b2954C1D1639", "proposalUrl": "https://www.tally.xyz/gov/gitcoin/proposal/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "Hop Protocol".to_string(),
            slug: "hop_protocol".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/hop-protocol".to_string(),
                background_color: "#d27ecc".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/hop.eth".to_string(),
                    decoder: json!({"snapshot_space": "hop.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::HopMainnet,
                    governance_portal: "https://www.tally.xyz/gov/hop".to_string(),
                    decoder: json!({"address": "0xed8Bdb5895B8B7f9Fdb3C087628FD8410E853D48", "proposalUrl": "https://www.tally.xyz/gov/hop/proposal/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "Uniswap".to_string(),
            slug: "uniswap".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/uniswap".to_string(),
                background_color: "#ffd5f5".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/uniswapgovernance.eth".to_string(),
                    decoder: json!({"snapshot_space": "uniswapgovernance.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::UniswapMainnet,
                    governance_portal: "https://app.uniswap.org/#/vote".to_string(),
                    decoder: json!({"address": "0x408ED6354d4973f66138C91495F2f2FCbd8724C3", "proxyAddress":"0x53a328f4086d7c0f1fa19e594c9b842125263026", "proposalUrl": "https://app.uniswap.org/#/vote/2/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "Optimism".to_string(),
            slug: "optimism".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/optimism".to_string(),
                background_color: "#ff444b".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/opcollective.eth".to_string(),
                    decoder: json!({"snapshot_space": "opcollective.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::OpOptimism,
                    governance_portal: "https://vote.optimism.io/proposals".to_string(),
                    decoder: json!({ "address": "0xcDF27F107725988f2261Ce2256bDfCdE8B382B10", "proposalUrl": "https://vote.optimism.io/proposals/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "Arbitrum DAO".to_string(),
            slug: "arbitrum_dao".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/arbitrum".to_string(),
                background_color: "#55677b".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/arbitrumfoundation.eth".to_string(),
                    decoder: json!({"snapshot_space": "arbitrumfoundation.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::ArbCoreArbitrum,
                    governance_portal: "https://www.tally.xyz/gov/arbitrum".to_string(),
                    decoder: json!({ "address": "0xf07DeD9dC292157749B6Fd268E37DF6EA38395B9", "proposalUrl": "https://www.tally.xyz/gov/arbitrum/proposal/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::ArbTreasuryArbitrum,
                    governance_portal: "https://www.tally.xyz/gov/arbitrum".to_string(),
                    decoder: json!({ "address": "0x789fC99093B09aD01C34DC7251D0C89ce743e5a4", "proposalUrl": "https://www.tally.xyz/gov/arbitrum/proposal/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "Frax".to_string(),
            slug: "frax".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/frax".to_string(),
                background_color: "#484848".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::Snapshot,
                    governance_portal: "https://snapshot.org/#/frax.eth".to_string(),
                    decoder: json!({"snapshot_space": "frax.eth"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1000,
                    votes_index: 0,
                    votes_refresh_speed: 0,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::FraxAlphaMainnet,
                    governance_portal: "https://app.frax.finance/gov/frax".to_string(),
                    decoder: json!({ "address": "0xe8Ab863E629a05c73D6a23b99d37027E3763156e", "proposalUrl": "https://app.frax.finance/gov/frax/proposals/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::FraxOmegaMainnet,
                    governance_portal: "https://app.frax.finance/gov/frax".to_string(),
                    decoder: json!({ "address": "0x953791d7c5ac8ce5fb23bbbf88963da37a95fe7a", "proposalUrl": "https://app.frax.finance/gov/frax/proposals/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
        DaoSeedData {
            name: "Nouns".to_string(),
            slug: "nouns".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/nouns".to_string(),
                background_color: "#904757".to_string(),
            },
            handlers: vec![HandlerData {
                handler_type: DaoHandlerEnumV2::NounsProposalsMainnet,
                governance_portal: "https://nouns.wtf/vote".to_string(),
                decoder: json!({ "address": "0x6f3E6272A167e8AcCb32072d08E0957F9c79223d", "proposalUrl": "https://nouns.wtf/vote/"}),
                refresh_enabled: true,
                proposals_index: 0,
                proposals_refresh_speed: 1_000_000,
                votes_index: 0,
                votes_refresh_speed: 1_000_000,
            }],
        },
        DaoSeedData {
            name: "MakerDAO".to_string(),
            slug: "makerdao".to_string(),
            hot: true,
            settings: SettingsData {
                picture: "assets/project-logos/makerdao".to_string(),
                background_color: "#68baaa".to_string(),
            },
            handlers: vec![
                HandlerData {
                    handler_type: DaoHandlerEnumV2::MakerExecutiveMainnet,
                    governance_portal: "https://vote.makerdao.com/executive".to_string(),
                    decoder: json!({ "address": "0x0a3f6849f78076aefaDf113F5BED87720274dDC0", "proposalUrl": "https://vote.makerdao.com/executive/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::MakerPollMainnet,
                    governance_portal: "https://vote.makerdao.com/polling/".to_string(),
                    decoder: json!({ "address_create": "0xf9be8f0945acddeedaa64dfca5fe9629d0cf8e5d", "address_vote": "0xD3A9FE267852281a1e6307a1C37CDfD76d39b133", "proposalUrl": "https://vote.makerdao.com/polling/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
                HandlerData {
                    handler_type: DaoHandlerEnumV2::MakerPollArbitrum,
                    governance_portal: "https://vote.makerdao.com/polling/".to_string(),
                    decoder: json!({ "address_vote": "0x4f4e551b4920a5417F8d4e7f8f099660dAdadcEC", "proposalUrl": "https://vote.makerdao.com/polling/"}),
                    refresh_enabled: true,
                    proposals_index: 0,
                    proposals_refresh_speed: 1_000_000,
                    votes_index: 0,
                    votes_refresh_speed: 1_000_000,
                },
            ],
        },
    ]
}
