apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    url: http://ch-server:8123
    server: ch-server
    port: 8123
    user: default
    jsonData:
      defaultDatabase: otel
      tlsSkipVerify: true
      queryTimeout: 30
      protocol: http
      mode: traces
      tracesTable: "otel_traces"
      logsTable: "otel_logs"
      logs:
        defaultDatabase: otel
        defaultTable: otel_logs
        otelEnabled: true
        otelVersion: "1.2.9"
        timeColumn: "Timestamp"
        severityTextColumn: "SeverityText"
        severityNumberColumn: "SeverityNumber"
        bodyColumn: "Body"
        traceIdColumn: "TraceId"
        spanIdColumn: "SpanId"
        resourceAttributesColumn: "ResourceAttributes"
        scopeNameColumn: "ScopeName"
        scopeVersionColumn: "ScopeVersion"
        scopeAttributesColumn: "ScopeAttributes"
        logAttributesColumn: "LogAttributes"
        droppedAttributesCountColumn: "DroppedAttributesCount"
        resourceSchemaUrlColumn: "ResourceSchemaUrl"
        scopeSchemaUrlColumn: "ScopeSchemaUrl"
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
        otelVersion: "1.2.9"
        durationUnit: "microseconds"
        traceIdColumn: "TraceId"
        spanIdColumn: "SpanId"
        parentSpanIdColumn: "ParentSpanId"
        traceStateColumn: "TraceState"
        spanNameColumn: "SpanName"
        spanKindColumn: "SpanKind"
        serviceNameColumn: "ServiceName"
        severityTextColumn: "SeverityText"
        resourceAttributesColumn: "ResourceAttributes"
        scopeNameColumn: "ScopeName"
        scopeVersionColumn: "ScopeVersion"
        spanAttributesColumn: "SpanAttributes"
        durationColumn: "Duration"
        statusCodeColumn: "StatusCode"
        statusMessageColumn: "StatusMessage"
        eventsTimestampColumn: "Events.Timestamp"
        eventsNameColumn: "Events.Name"
        eventsAttributesColumn: "Events.Attributes"
        linksTraceIdColumn: "Links.TraceId"
        linksSpanIdColumn: "Links.SpanId"
        linksTraceStateColumn: "Links.TraceState"
        linksAttributesColumn: "Links.Attributes"
        droppedAttributesCountColumn: "DroppedAttributesCount"
        droppedEventsCountColumn: "DroppedEventsCount"
        droppedLinksCountColumn: "DroppedLinksCount"
        resourceSchemaUrlColumn: "ResourceSchemaUrl"
        scopeSchemaUrlColumn: "ScopeSchemaUrl"
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
    editable: true
    isDefault: true
