---
- name: Install PostgreSQL with Patroni HA
  hosts: postgres_nodes
  become: true
  vars:
    postgresql_version: "17"
    patroni_version: "4.0.6"
    postgres_version: "17"
    postgres_port: 5432
    patroni_rest_api_port: 8008
    consul_client_port: 8500
    postgres_password: "{{ vault_postgres_password }}"
    postgres_replication_password: "{{ vault_postgres_replication_password }}"
    postgres_user: "postgres"
    postgres_db_name: "proposalsapp"
    # Resource settings - adjust based on server RAM
    postgres_shared_buffers: "2GB"
    postgres_effective_cache_size: "6GB"
    postgres_work_mem: "16MB"

  tasks:
    - name: Set connection to use tailscale IP if available
      set_fact:
        ansible_host: "{{ tailscale_ip }}"
      when: tailscale_ip is defined and tailscale_ip != ''
    
    # Pre-flight check: Ensure Consul is properly federated
    - name: Verify Consul WAN federation
      shell: |
        # Check if Consul can see all datacenters
        datacenters=$(consul catalog datacenters | wc -l)
        expected_dcs={{ groups['lxc_containers'] | select('match', '^consul-nomad-') | map('extract', hostvars, 'datacenter') | unique | list | length }}
        
        if [ "$datacenters" -lt "$expected_dcs" ]; then
          echo "ERROR: Consul federation incomplete. Found $datacenters datacenters, expected $expected_dcs"
          echo "Available datacenters:"
          consul catalog datacenters
          exit 1
        fi
        
        echo "OK: Consul federation verified across $datacenters datacenters"
      register: consul_federation
      changed_when: false
      run_once: true
      delegate_to: "{{ groups['consul_servers'][0] }}"
    - name: Add PostgreSQL APT key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: Add PostgreSQL repository
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
        state: present

    - name: Install PostgreSQL and dependencies
      apt:
        name:
          - "postgresql-{{ postgresql_version }}"
          - "postgresql-contrib-{{ postgresql_version }}"
          - "postgresql-{{ postgresql_version }}-repack"
          - python3-pip
          - python3-psycopg2
          - python3-etcd
          - libpq-dev
        state: present

    - name: Check PostgreSQL service status
      systemd:
        name: postgresql
      register: postgresql_service
      failed_when: false

    - name: Stop PostgreSQL service
      systemd:
        name: postgresql
        state: stopped
        enabled: no
      when: postgresql_service.status.ActiveState is defined and postgresql_service.status.ActiveState == "active"

    - name: Install pipx and venv support
      apt:
        name:
          - pipx
          - python3-venv
          - python3-full
        state: present

    - name: Check if Patroni is already installed
      stat:
        path: /var/lib/postgresql/.local/bin/patroni
      register: patroni_installed

    - name: Install Patroni and dependencies for postgres user
      shell: |
        su - postgres -c '
        export PATH="/usr/bin:$PATH"
        pipx install "patroni[consul]=={{ patroni_version }}" --include-deps
        pipx inject patroni psycopg2-binary python-consul cdiff
        '
      when: not patroni_installed.stat.exists

    - name: Ensure Patroni has all dependencies
      shell: |
        su - postgres -c '
        export PATH="/usr/bin:$PATH"
        pipx inject patroni cdiff --force
        '
      when: patroni_installed.stat.exists

    - name: Create Patroni configuration directory
      file:
        path: /etc/patroni
        state: directory
        mode: "0755"

    - name: Create PostgreSQL data directory
      file:
        path: /var/lib/postgresql/{{ postgresql_version }}/data
        state: directory
        owner: postgres
        group: postgres
        mode: "0700"


    - name: Generate Patroni configuration
      template:
        src: ../templates/patroni.yml.j2
        dest: /etc/patroni/patroni.yml
        owner: postgres
        group: postgres
        mode: "0640"

    - name: Create Patroni systemd service
      copy:
        content: |
          [Unit]
          Description=Patroni PostgreSQL HA
          After=syslog.target network.target consul.service
          Wants=consul.service

          [Service]
          Type=simple
          User=postgres
          Group=postgres
          Environment="PATH=/var/lib/postgresql/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          ExecStart=/var/lib/postgresql/.local/bin/patroni /etc/patroni/patroni.yml
          ExecReload=/bin/kill -s HUP $MAINPID
          KillMode=process
          TimeoutSec=30
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/patroni.service
      notify:
        - reload systemd
        - restart patroni

    # Clean any existing Patroni state to ensure fresh start
    - name: Clean existing Patroni state from Consul
      uri:
        url: "http://localhost:{{ consul_client_port }}/v1/kv/service/proposalsapp?recurse=true"
        method: DELETE
        status_code: [200, 404]
      run_once: true
      delegate_to: "{{ groups['consul_servers'][0] }}"
      when: postgres_role == 'primary'

    - name: Start Patroni service on primary node first
      systemd:
        name: patroni
        state: started
        enabled: yes
      when: postgres_role == 'primary'

    - name: Wait for primary PostgreSQL to be ready
      wait_for:
        port: 5432
        host: localhost
        delay: 10
        timeout: 120
      when: postgres_role == 'primary'

    - name: Verify cluster initialization on primary
      shell: |
        # Wait for Patroni to initialize and register in Consul
        for i in {1..30}; do
          if /var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml list | grep -q "Leader"; then
            echo "Primary node initialized successfully"
            exit 0
          fi
          sleep 2
        done
        echo "ERROR: Primary failed to initialize"
        exit 1
      when: postgres_role == 'primary'
      register: primary_init
      failed_when: primary_init.rc != 0

    - name: Pause to ensure primary is fully registered in Consul
      pause:
        seconds: 15
      run_once: true

    - name: Start Patroni service on standby nodes
      systemd:
        name: patroni
        state: started
        enabled: yes
      when: postgres_role != 'primary'

    - name: Wait for standby nodes to join cluster
      shell: |
        # Wait for this node to appear in the cluster
        for i in {1..60}; do
          if /var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml list | grep -q "{{ inventory_hostname }}"; then
            echo "Node joined cluster successfully"
            exit 0
          fi
          sleep 2
        done
        echo "ERROR: Failed to join cluster"
        exit 1
      when: postgres_role != 'primary'
      register: standby_join
      failed_when: standby_join.rc != 0

    - name: Check if PostgreSQL service is already registered
      uri:
        url: "http://localhost:{{ consul_client_port }}/v1/agent/service/postgres-{{ inventory_hostname }}"
        method: GET
        status_code: [200, 404]
      register: postgres_service_check
      changed_when: false

    - name: Register PostgreSQL services in Consul
      uri:
        url: "http://localhost:{{ consul_client_port }}/v1/agent/service/register"
        method: PUT
        body_format: json
        body:
          ID: "postgres-{{ inventory_hostname }}"
          Name: "postgres"
          Tags:
            - "{{ postgres_role }}"
            - "{{ datacenter }}"
          Port: 5432
          Check:
            TCP: "localhost:5432"
            Interval: "10s"
      when: postgres_service_check.status == 404

    - name: Wait for PostgreSQL to be ready
      wait_for:
        port: 5432
        host: localhost
        delay: 5
        timeout: 60


    - name: Store PostgreSQL connection details in Consul KV
      uri:
        url: "http://localhost:{{ consul_client_port }}/v1/kv/{{ item.key }}"
        method: PUT
        body: "{{ item.value }}"
      loop:
        - { key: "postgresql/primary_host", value: "{{ inventory_hostname }}" }
        - { key: "postgresql/primary_tailscale_ip", value: "{{ tailscale_ip }}" }
        - { key: "postgresql/port", value: "5432" }
        - { key: "postgresql/database", value: "{{ postgres_db_name }}" }
        - { key: "postgresql/username", value: "proposalsapp" }
        - { key: "postgresql/admin_username", value: "{{ postgres_user }}" }
        - { key: "postgresql/password", value: "{{ postgres_password }}" }
        - { key: "postgresql/service_discovery", value: "proposalsapp.service.consul" }
        - { key: "postgresql/connection_string/consul", value: "postgresql://proposalsapp:{{ postgres_password }}@proposalsapp.service.consul:5432/{{ postgres_db_name }}" }
        - { key: "postgresql/connection_string/hostname", value: "postgresql://proposalsapp:{{ postgres_password }}@{{ inventory_hostname }}:5432/{{ postgres_db_name }}" }
        - { key: "postgresql/connection_string/tailscale_ip", value: "postgresql://proposalsapp:{{ postgres_password }}@{{ tailscale_ip }}:5432/{{ postgres_db_name }}" }
        - { key: "database/name", value: "{{ postgres_db_name }}" }
        - { key: "database/user", value: "proposalsapp" }
        - { key: "database/password", value: "{{ postgres_password }}" }
      run_once: true
      when: postgres_role == 'primary'

    - name: Wait for all PostgreSQL nodes to join cluster
      pause:
        seconds: 30
      run_once: true

    - name: Verify all nodes are in cluster before configuring replication
      shell: |
        # Get the expected number of nodes
        expected_nodes={{ groups['postgres_nodes'] | length }}
        
        # Count actual nodes in cluster
        actual_nodes=$(/var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml list | grep -E "Leader|Replica" | wc -l)
        
        echo "Expected nodes: $expected_nodes, Actual nodes: $actual_nodes"
        
        if [ "$actual_nodes" -eq "$expected_nodes" ]; then
          echo "All nodes are in the cluster"
          exit 0
        else
          echo "WARNING: Not all nodes have joined the cluster yet"
          exit 1
        fi
      register: cluster_check
      until: cluster_check.rc == 0
      retries: 10
      delay: 10
      when: postgres_role == 'primary'
      run_once: true

    - name: Configure synchronous replication with proper standby names
      shell: |
        # Get list of standby nodes from the cluster
        standby_nodes=$(/var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml list | grep "Replica" | awk '{print $2}' | tr '\n' ',' | sed 's/,$//')
        
        if [ -n "$standby_nodes" ]; then
          echo "Found standby nodes: $standby_nodes"
          
          # Count replicas
          replica_count=$(echo "$standby_nodes" | tr ',' '\n' | wc -l)
          
          # Build synchronous_standby_names based on datacenter distribution
          # Use ANY 1 syntax for quorum-based replication
          sync_standby_names="ANY 1 ($standby_nodes)"
          
          echo "Enabling synchronous replication with: $sync_standby_names"
          
          # Enable synchronous mode in Patroni
          /var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml edit-config \
            -s "synchronous_mode=true" \
            -s "synchronous_mode_strict=false" \
            -s "postgresql.parameters.synchronous_commit=remote_apply" \
            -s "postgresql.parameters.synchronous_standby_names='$sync_standby_names'" \
            --force
          
          echo "Synchronous replication enabled with $replica_count replicas"
        else
          echo "No replicas found, keeping synchronous mode disabled"
          
          # Ensure async parameters are set
          /var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml edit-config \
            -s "synchronous_mode=false" \
            -s "postgresql.parameters.synchronous_commit=on" \
            -s "postgresql.parameters.synchronous_standby_names=" \
            --force
        fi
      register: sync_result
      changed_when: "'Synchronous replication enabled' in sync_result.stdout"
      run_once: true
      when: postgres_role == 'primary'

    - name: Wait for database initialization to complete
      pause:
        seconds: 10
      when: postgres_role == 'primary'

    - name: Verify database and user creation on primary
      shell: |
        export PGPASSWORD="{{ postgres_password }}"
        
        # First check if we can connect as postgres user
        if ! psql -h localhost -U postgres -d postgres -c "SELECT 1;" >/dev/null 2>&1; then
          echo "ERROR: Cannot connect to PostgreSQL as postgres user"
          exit 1
        fi
        
        # Check if user exists (user should be created by Patroni bootstrap config)
        if ! psql -h localhost -U postgres -d postgres -tAc "SELECT 1 FROM pg_user WHERE usename='proposalsapp';" | grep -q 1; then
          echo "ERROR: proposalsapp user not created by Patroni bootstrap"
          exit 1
        fi
        
        # Check if database exists (database should be created by Patroni bootstrap config)
        if ! psql -h localhost -U postgres -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='proposalsapp';" | grep -q 1; then
          echo "ERROR: proposalsapp database not created by Patroni bootstrap"
          exit 1
        fi
        
        # Test connection as proposalsapp user
        export PGPASSWORD="{{ postgres_password }}"
        if ! psql -h localhost -U proposalsapp -d proposalsapp -c "SELECT version();" >/dev/null 2>&1; then
          echo "ERROR: Cannot connect as proposalsapp user"
          exit 1
        fi
        
        echo "SUCCESS: Database and user are properly configured"
      when: postgres_role == 'primary'
      changed_when: false
      retries: 3
      delay: 5
      register: db_verify
      until: db_verify.rc == 0

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart patroni
      systemd:
        name: patroni
        state: restarted


# Verification checks at the end
- name: Verify PostgreSQL Cluster
  hosts: postgres_nodes
  gather_facts: false
  vars:
    postgres_user: "postgres"
    postgres_db_name: "proposalsapp"
    postgres_password: "{{ vault_postgres_password }}"
    consul_client_port: 8500
  tasks:
    - name: Wait for PostgreSQL to stabilize
      pause:
        seconds: 15

    - name: Check Patroni service health
      shell: |
        # Check if Patroni is running
        if ! systemctl is-active patroni >/dev/null 2>&1; then
          echo "ERROR: Patroni service is not running"
          exit 1
        fi

        echo "OK: Patroni service is active"
      register: patroni_health
      changed_when: false
      failed_when: patroni_health.rc != 0

    - name: Check Patroni cluster status
      shell: |
        # Check Patroni cluster status
        cluster_info=$(/var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml list 2>&1)
        if [ $? -ne 0 ]; then
          echo "ERROR: Cannot query Patroni cluster: $cluster_info"
          exit 1
        fi

        # Check if this node is in the cluster
        if ! echo "$cluster_info" | grep -q "{{ inventory_hostname }}"; then
          echo "ERROR: This node is not in the Patroni cluster"
          echo "$cluster_info"
          exit 1
        fi

        # Check for a leader (but allow time for election during initial setup)
        if ! echo "$cluster_info" | grep -q -E "(Leader|initializing)"; then
          echo "ERROR: No leader in Patroni cluster and not initializing"
          echo "$cluster_info"
          exit 1
        fi

        echo "OK: Patroni cluster healthy"
        echo "$cluster_info"
      register: patroni_cluster
      changed_when: false
      failed_when: patroni_cluster.rc != 0

    - name: Check PostgreSQL connectivity
      shell: |
        export PGPASSWORD="{{ postgres_password }}"
        if ! psql -h localhost -U {{ postgres_user }} -d postgres -c "SELECT version();" >/dev/null 2>&1; then
          echo "ERROR: Cannot connect to PostgreSQL"
          exit 1
        fi

        echo "OK: PostgreSQL is accessible"
      register: postgres_connectivity
      changed_when: false
      failed_when: postgres_connectivity.rc != 0

    - name: Verify Consul service registration
      shell: |
        # Check if PostgreSQL service is registered in Consul
        service_info=$(curl -s http://localhost:{{ consul_client_port }}/v1/agent/service/postgres-{{ inventory_hostname }})
        if [ $? -ne 0 ] || [ -z "$service_info" ] || [ "$service_info" = "null" ]; then
          echo "ERROR: PostgreSQL service not registered in Consul"
          exit 1
        fi

        echo "OK: PostgreSQL service registered in Consul"
        echo "$service_info" | jq -r '.ID + " - " + .Service + " - Port: " + (.Port|tostring)'
      register: consul_service
      changed_when: false
      failed_when: consul_service.rc != 0

    - name: Display PostgreSQL verification summary
      debug:
        msg: |
          ========================================
          PostgreSQL Cluster Verification Summary
          ========================================
          Node: {{ inventory_hostname }}
          Patroni Status: {{ 'RUNNING' if patroni_health.rc == 0 else 'FAILED' }}
          Cluster Health: {{ 'HEALTHY' if patroni_cluster.rc == 0 else 'UNHEALTHY' }}
          PostgreSQL Access: {{ 'OK' if postgres_connectivity.rc == 0 else 'FAILED' }}
          Consul Registration: {{ 'REGISTERED' if consul_service.rc == 0 else 'NOT REGISTERED' }}

          Cluster Status:
          {{ patroni_cluster.stdout | indent(2) }}

          Connection Details:
          - Direct PostgreSQL: {{ inventory_hostname }}:5432
          - Database: {{ postgres_db_name }}
          - Note: Applications should connect via PgCat on localhost:5432
          - User: {{ postgres_user }}
          ========================================

- name: Display Overall Cluster Summary
  hosts: postgres_nodes[0]
  gather_facts: false
  tasks:
    - name: Get full cluster overview
      shell: |
        echo "=== PATRONI CLUSTER OVERVIEW ==="
        patronictl -c /etc/patroni/patroni.yml list
        echo ""
        echo "=== REPLICATION STATUS ==="
        export PGPASSWORD="{{ postgres_password }}"
        psql -h localhost -U {{ postgres_user }} -d postgres -c "SELECT client_addr, state, sync_state FROM pg_stat_replication;" 2>/dev/null || echo "No replicas (this might be a replica node)"
      register: cluster_overview
      changed_when: false

    - name: Display cluster overview
      debug:
        msg: |
          ========================================
          PostgreSQL HA Cluster Overview
          ========================================
          {{ cluster_overview.stdout }}
          ========================================
