---
- name: Fix db-sib-03 PostgreSQL node
  hosts: db-sib-03
  become: true
  vars:
    postgres_password: "{{ vault_postgres_password }}"
    consul_client_port: 8500
  tasks:
    - name: Check current Patroni status
      shell: |
        systemctl status patroni
        echo "---"
        /var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml list || true
      register: current_status
      failed_when: false

    - name: Display current status
      debug:
        msg: "{{ current_status.stdout }}"

    - name: Stop Patroni service
      systemd:
        name: patroni
        state: stopped

    - name: Clean PostgreSQL data directory
      file:
        path: /var/lib/postgresql/17/data
        state: absent

    - name: Create fresh data directory
      file:
        path: /var/lib/postgresql/17/data
        state: directory
        owner: postgres
        group: postgres
        mode: "0700"

    - name: Wait for cluster to stabilize
      pause:
        seconds: 10

    - name: Start Patroni service
      systemd:
        name: patroni
        state: started

    - name: Wait for node to join cluster as replica
      shell: |
        #!/bin/bash
        i=1
        while [ $i -le 90 ]; do
          cluster_output=$(/var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml list 2>&1)
          
          # Check if this node appears in the cluster output
          if echo "$cluster_output" | grep -q "db-sib-03"; then
            # Check if it is in streaming state
            if echo "$cluster_output" | grep "db-sib-03" | grep -qE "(streaming|running)"; then
              echo "Node joined cluster successfully"
              echo "$cluster_output"
              exit 0
            else
              echo "Node found but not yet streaming... (attempt $i/90)"
            fi
          else
            echo "Waiting for node to join cluster... (attempt $i/90)"
          fi
          sleep 3
          i=$((i + 1))
        done
        echo "ERROR: Failed to join cluster after 270 seconds"
        echo "Final status:"
        /var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml list
        echo ""
        echo "Patroni logs:"
        journalctl -u patroni -n 50 --no-pager
        exit 1
      args:
        executable: /bin/bash
      register: join_status

    - name: Verify cluster has all 3 nodes
      shell: |
        cluster_output=$(/var/lib/postgresql/.local/bin/patronictl -c /etc/patroni/patroni.yml list)
        echo "$cluster_output"
        
        # Count nodes in cluster
        node_count=$(echo "$cluster_output" | grep -E "(Leader|Replica)" | wc -l)
        
        if [ "$node_count" -eq "3" ]; then
          echo ""
          echo "SUCCESS: All 3 nodes are in the cluster"
          exit 0
        else
          echo ""
          echo "ERROR: Expected 3 nodes, found $node_count"
          exit 1
        fi
      register: final_cluster
      delegate_to: db-sib-01

    - name: Display final cluster status
      debug:
        msg: "{{ final_cluster.stdout }}"