---
- name: Setup simplified deployment automation
  hosts: consul-nomad-sib-01
  become: true
  vars:
    deployment_dir: /opt/deployment
    
  tasks:
    - name: Stop and disable old watcher service if exists
      systemd:
        name: consul-deployment-watcher
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Create deployment directory
      file:
        path: "{{ deployment_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy deployment checker script
      copy:
        src: ../files/deployment-checker.sh
        dest: "{{ deployment_dir }}/deployment-checker.sh"
        owner: root
        group: root
        mode: '0755'

    - name: Create systemd service for deployment checker
      copy:
        dest: /etc/systemd/system/deployment-checker.service
        content: |
          [Unit]
          Description=Deployment Checker
          After=consul.service nomad.service
          Requires=consul.service

          [Service]
          Type=oneshot
          ExecStart={{ deployment_dir }}/deployment-checker.sh
          StandardOutput=journal
          StandardError=journal
          SyslogIdentifier=deployment-checker

    - name: Create systemd timer for deployment checker
      copy:
        dest: /etc/systemd/system/deployment-checker.timer
        content: |
          [Unit]
          Description=Run deployment checker every minute
          Requires=deployment-checker.service

          [Timer]
          OnBootSec=1min
          OnUnitActiveSec=1min

          [Install]
          WantedBy=timers.target

    - name: Start and enable deployment checker timer
      systemd:
        name: deployment-checker.timer
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Run initial deployment check
      command: "{{ deployment_dir }}/deployment-checker.sh"
      register: initial_check

    - name: Show initial check result
      debug:
        msg: "{{ initial_check.stdout_lines }}"

    - name: Show deployment automation status
      debug:
        msg: |
          ========================================
          Simplified Deployment Automation Active
          ========================================
          
          The system now checks for deployment updates every minute.
          
          How it works:
          1. GitHub Actions builds and updates Consul KV
          2. Deployment checker runs every minute
          3. If image changed, it updates Nomad job
          4. Nomad performs rolling deployment
          
          Monitor with:
          - journalctl -u deployment-checker -f
          - systemctl status deployment-checker.timer
          - tail -f /var/log/deployment-checker.log
          
          ========================================"