---
- name: Setup Consul KV values for rindexer in all datacenters
  hosts: consul_servers
  become: true
  vars:
    consul_kv_values:
      # Blockchain RPC endpoints
      - key: "rindexer/ethereum_node_url"
        value: "{{ vault_rindexer_ethereum_node_url }}"
      - key: "rindexer/arbitrum_node_url"
        value: "{{ vault_rindexer_arbitrum_node_url }}"
      - key: "rindexer/optimism_node_url"
        value: "{{ vault_rindexer_optimism_node_url }}"
      - key: "rindexer/avalanche_node_url"
        value: "{{ vault_rindexer_avalanche_node_url }}"
      - key: "rindexer/polygon_node_url"
        value: "{{ vault_rindexer_polygon_node_url }}"

      # Block explorer API keys
      - key: "rindexer/etherscan_api_key"
        value: "{{ vault_rindexer_etherscan_api_key }}"
      - key: "rindexer/arbiscan_api_key"
        value: "{{ vault_rindexer_arbiscan_api_key }}"
      - key: "rindexer/optimistic_scan_api_key"
        value: "{{ vault_rindexer_optimistic_scan_api_key }}"

      # OpenTelemetry configuration
      - key: "rindexer/otel_exporter_otlp_endpoint"
        value: "{{ vault_otel_exporter_otlp_endpoint }}"

  tasks:
    - name: Ensure Consul is available
      wait_for:
        port: 8500
        host: localhost
        timeout: 60

    - name: Get local Consul datacenter info
      uri:
        url: "http://localhost:8500/v1/agent/self"
        method: GET
      register: consul_info

    - name: Set datacenter variable
      set_fact:
        current_datacenter: "{{ consul_info.json.Config.Datacenter }}"

    - name: Store values in local datacenter's Consul KV
      uri:
        url: "http://localhost:8500/v1/kv/{{ item.key }}"
        method: PUT
        body: "{{ item.value }}"
      loop: "{{ consul_kv_values }}"
      loop_control:
        label: "{{ item.key }} in {{ current_datacenter }}"
      no_log: true # Don't log sensitive values

    - name: Display setup information for this datacenter
      debug:
        msg: |
          ========================================
          Consul KV Setup Complete for {{ current_datacenter }}
          ========================================

          Environment variables have been stored in Consul KV
          for datacenter: {{ current_datacenter }}

          Run this playbook on all consul servers to replicate
          the configuration across all datacenters.
          ========================================
      run_once: true

- name: Display final deployment instructions
  hosts: localhost
  connection: local
  tasks:
    - name: Show deployment instructions
      debug:
        msg: |
          ========================================
          Rindexer Setup Complete
          ========================================

          To deploy rindexer:
          1. Ensure this playbook has been run on all consul servers
          2. Run: nomad job run infrastructure/ansible/applications/rindexer/rindexer.nomad

          Rindexer always deploys from the main branch.
          Feature branches are built and stored in ghcr.io but not automatically deployed.

          To verify the values in each datacenter:
          - consul kv get rindexer/ethereum_node_url
          - consul kv get pgcat/connection_string/local
          - consul kv get rindexer/image/main

          The rindexer service will automatically:
          - Connect to the local PgCat instance using the connection string from Consul KV
          - Use the configured RPC endpoints for blockchain indexing
          - Send metrics to the observability stack
          - Pull the latest Docker image from the main branch

          Note: Database credentials are securely stored in Consul KV by the PgCat playbook
          ========================================
