---
- name: Setup Consul KV values for rindexer in all datacenters
  hosts: consul_servers
  become: true
  vars:
    consul_kv_values:
      # Block explorer API keys
      - key: "rindexer/etherscan_api_key"
        value: "{{ vault_rindexer_etherscan_api_key }}"
      - key: "rindexer/arbiscan_api_key"
        value: "{{ vault_rindexer_arbiscan_api_key }}"
      - key: "rindexer/optimistic_scan_api_key"
        value: "{{ vault_rindexer_optimistic_scan_api_key }}"
      - key: "rindexer/polygonscan_api_key"
        value: "{{ vault_rindexer_polygonscan_api_key | default('') }}"

      # BetterStack monitoring
      - key: "rindexer/betterstack_key"
        value: "{{ vault_rindexer_betterstack_key }}"

  tasks:
    - name: Ensure Consul is available
      wait_for:
        port: 8500
        host: localhost
        timeout: 60

    - name: Get local Consul datacenter info
      uri:
        url: "http://localhost:8500/v1/agent/self"
        method: GET
      register: consul_info

    - name: Set datacenter variable
      set_fact:
        current_datacenter: "{{ consul_info.json.Config.Datacenter }}"

    - name: Store values in local datacenter's Consul KV
      uri:
        url: "http://localhost:8500/v1/kv/{{ item.key }}"
        method: PUT
        body: "{{ item.value }}"
      loop: "{{ consul_kv_values }}"
      loop_control:
        label: "{{ item.key }} in {{ current_datacenter }}"
      no_log: true # Don't log sensitive values

    - name: Display setup completion
      debug:
        msg: "Consul KV setup complete for rindexer in {{ current_datacenter }}"
      run_once: true
