//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "governor_new"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: Uuid,
    pub dao_id: Uuid,
    pub name: String,
    pub r#type: String,
    pub metadata: Json,
    pub enabled: bool,
    pub portal_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    DaoId,
    Name,
    Type,
    Metadata,
    Enabled,
    PortalUrl,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Dao,
    ProposalNew,
    VoteNew,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::DaoId => ColumnType::Uuid.def(),
            Self::Name => ColumnType::Text.def(),
            Self::Type => ColumnType::Text.def(),
            Self::Metadata => ColumnType::JsonBinary.def(),
            Self::Enabled => ColumnType::Boolean.def(),
            Self::PortalUrl => ColumnType::Text.def().null(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Dao => Entity::belongs_to(super::dao::Entity)
                .from(Column::DaoId)
                .to(super::dao::Column::Id)
                .into(),
            Self::ProposalNew => Entity::has_many(super::proposal_new::Entity).into(),
            Self::VoteNew => Entity::has_many(super::vote_new::Entity).into(),
        }
    }
}

impl Related<super::dao::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dao.def()
    }
}

impl Related<super::proposal_new::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProposalNew.def()
    }
}

impl Related<super::vote_new::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VoteNew.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
