//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "snapshot_message"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub mci: i64,
    pub space: String,
    pub r#type: String,
    pub ipfs: String,
    pub address: String,
    pub timestamp: i64,
    pub related_proposal_id: Option<String>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    Mci,
    Space,
    Type,
    Ipfs,
    Address,
    Timestamp,
    RelatedProposalId,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = String;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Mci => ColumnType::BigInteger.def(),
            Self::Space => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Type => ColumnType::String(StringLen::N(50u32)).def(),
            Self::Ipfs => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Address => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Timestamp => ColumnType::BigInteger.def(),
            Self::RelatedProposalId => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
