# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio
networks:
- id: 42161
  start_block: 0
  contracts:
  - name: TransparentUpgradeableProxy
    address:
    - 0xf07DeD9dC292157749B6Fd268E37DF6EA38395B9
    handler: src/EventHandlers.ts
    events:
    - event: ProposalCanceled(uint256 proposalId)
    - event: ProposalCreated(uint256 proposalId, address proposer, address[] targets, uint256[] values, string[] signatures, bytes[] calldatas, uint256 startBlock, uint256 endBlock, string description)
    - event: ProposalExecuted(uint256 proposalId)
    - event: ProposalExtended(uint256 indexed proposalId, uint64 extendedDeadline)
    - event: ProposalQueued(uint256 proposalId, uint256 eta)
    - event: VoteCast(address indexed voter, uint256 proposalId, uint8 support, uint256 weight, string reason)
    - event: VoteCastWithParams(address indexed voter, uint256 proposalId, uint8 support, uint256 weight, string reason, bytes params)
rollback_on_reorg: false
