[alias]
t = "nextest run -- --include-ignored"
t-ci = "nextest run"
lint = "clippy --workspace --all-targets --all-features -- -D warnings"
fix = "clippy --workspace --all-targets --all-features --fix --allow-dirty --allow-staged -- -D warnings"
format = "fmt --all"
check-format = "fmt --all -- --check"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
