"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _arbitrum_summary_header from './arbitrum-summary-header.bones.json'
import _uniswap_summary_header from './uniswap-summary-header.bones.json'
import _groups_header from './groups-header.bones.json'
import _main_page from './main-page.bones.json'
import _group_list from './group-list.bones.json'
import _active_group_item from './active-group-item.bones.json'
import _inactive_group_item from './inactive-group-item.bones.json'
import _discussion_group_item from './discussion-group-item.bones.json'
import _group_page from './group-page.bones.json'
import _body_header from './body-header.bones.json'
import _body from './body.bones.json'
import _menu_bar_full from './menu-bar-full.bones.json'
import _menu_bar_body from './menu-bar-body.bones.json'
import _menu_bar_comments from './menu-bar-comments.bones.json'
import _initially_posted from './initially-posted.bones.json'
import _posted_revisions from './posted-revisions.bones.json'
import _feed from './feed.bones.json'
import _post_item from './post-item.bones.json'
import _vote_item_feed from './vote-item-feed.bones.json'
import _results_page from './results-page.bones.json'
import _results_header from './results-header.bones.json'
import _results_content from './results-content.bones.json'
import _results_title from './results-title.bones.json'
import _results_list from './results-list.bones.json'
import _results_list_bars from './results-list-bars.bones.json'
import _chart from './chart.bones.json'
import _results_table from './results-table.bones.json'
import _non_voters_table from './non-voters-table.bones.json'
import _timeline from './timeline.bones.json'
import _nav_shell from './nav-shell.bones.json'
import _mode_toggle from './mode-toggle.bones.json'
import _profile_page from './profile-page.bones.json'
import _onboarding_page from './onboarding-page.bones.json'
import _mapping_page from './mapping-page.bones.json'
import _delegates_page from './delegates-page.bones.json'

registerBones({
  "arbitrum-summary-header": _arbitrum_summary_header,
  "uniswap-summary-header": _uniswap_summary_header,
  "groups-header": _groups_header,
  "main-page": _main_page,
  "group-list": _group_list,
  "active-group-item": _active_group_item,
  "inactive-group-item": _inactive_group_item,
  "discussion-group-item": _discussion_group_item,
  "group-page": _group_page,
  "body-header": _body_header,
  "body": _body,
  "menu-bar-full": _menu_bar_full,
  "menu-bar-body": _menu_bar_body,
  "menu-bar-comments": _menu_bar_comments,
  "initially-posted": _initially_posted,
  "posted-revisions": _posted_revisions,
  "feed": _feed,
  "post-item": _post_item,
  "vote-item-feed": _vote_item_feed,
  "results-page": _results_page,
  "results-header": _results_header,
  "results-content": _results_content,
  "results-title": _results_title,
  "results-list": _results_list,
  "results-list-bars": _results_list_bars,
  "chart": _chart,
  "results-table": _results_table,
  "non-voters-table": _non_voters_table,
  "timeline": _timeline,
  "nav-shell": _nav_shell,
  "mode-toggle": _mode_toggle,
  "profile-page": _profile_page,
  "onboarding-page": _onboarding_page,
  "mapping-page": _mapping_page,
  "delegates-page": _delegates_page,
})
