---
- name: Setup Consul KV values for web in all datacenters
  hosts: consul_servers
  become: true
  vars:
    consul_kv_values:
      # Application configuration
      - key: "web/root_domain"
        value: "{{ vault_web_root_domain }}"
      - key: "web/special_subdomains"
        value: "{{ vault_web_special_subdomains }}"

      # Analytics
      - key: "web/posthog_key"
        value: "{{ vault_web_posthog_key }}"

      # Web Push configuration
      - key: "web/web_push_public_key"
        value: "{{ vault_web_push_public_key }}"
      - key: "web/web_push_private_key"
        value: "{{ vault_web_push_private_key }}"
      - key: "web/web_push_email"
        value: "{{ vault_web_push_email }}"

      # Email service
      - key: "web/resend_api_key"
        value: "{{ vault_resend_api_key }}"
      - key: "web/better_auth_secret"
        value: "{{ vault_web_better_auth_secret }}"

      # Tally API
      - key: "web/tally_api_key"
        value: "{{ vault_tally_api_key }}"

  tasks:
    - name: Ensure Consul is available
      wait_for:
        port: 8500
        host: localhost
        timeout: 60

    - name: Get local Consul datacenter info
      uri:
        url: "http://localhost:8500/v1/agent/self"
        method: GET
      register: consul_info

    - name: Set datacenter variable
      set_fact:
        current_datacenter: "{{ consul_info.json.Config.Datacenter }}"

    - name: Store values in local datacenter's Consul KV
      uri:
        url: "http://localhost:8500/v1/kv/{{ item.key }}"
        method: PUT
        body: "{{ item.value }}"
      loop: "{{ consul_kv_values }}"
      loop_control:
        label: "{{ item.key }} in {{ current_datacenter }}"
      no_log: true # Don't log sensitive values

    - name: Display setup completion
      debug:
        msg: "Consul KV setup complete for web application in {{ current_datacenter }}"
      run_once: true
