//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub mod prelude;

pub mod dao;
pub mod dao_discourse;
pub mod dao_governor;
pub mod delegate;
pub mod delegate_to_discourse_user;
pub mod delegate_to_voter;
pub mod delegation;
pub mod discourse_category;
pub mod discourse_post;
pub mod discourse_post_like;
pub mod discourse_post_revision;
pub mod discourse_topic;
pub mod discourse_user;
pub mod job_queue;
pub mod kysely_migration;
pub mod kysely_migration_lock;
pub mod proposal;
pub mod proposal_group;
pub mod sea_orm_active_enums;
pub mod vote;
pub mod voter;
pub mod voting_power;
