[store]
dir = "target/nextest"

[profile.default]
retries = { backoff = "exponential", count = 3, delay = "10s", jitter = true, max-delay = "60s" }
slow-timeout = { period = "600s", terminate-after = 4 }
test-threads = 1
fail-fast = false

[profile.default.junit]
path = "junit.xml"
report-name = "nextest-run"
store-success-output = true
store-failure-output = true
