services:
  erpc:
    image: ghcr.io/erpc/erpc:latest
    ports:
      - "4000:4000"
    volumes:
      - ./erpc.yaml:/root/erpc.yaml
    restart: unless-stopped
    environment:
      ERPC_ALCHEMY_KEY: ${ERPC_ALCHEMY_KEY}
      ERPC_REDIS_URL: ${ERPC_REDIS_URL}
      ERPC_REIDS_PASSWORD: ${ERPC_REIDS_PASSWORD}
