services:
  erpc:
    image: ghcr.io/erpc/erpc:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
      - "4001:4001"
    volumes:
      - ./erpc.yaml:/root/erpc.yaml
    environment:
      ERPC_ALCHEMY_KEY: ${ERPC_ALCHEMY_KEY}
      ERPC_BLAST_KEY: ${ERPC_BLAST_KEY}
      ERPC_DRPC_KEY: ${ERPC_DRPC_KEY}
    networks:
      - erpc_network

  monitoring:
    build: ./monitoring
    restart: unless-stopped
    ports:
      - "3000:3000" # Grafana
      - "9090:9090" # Prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
      - prometheus_data:/prometheus
      - grafana_data:/var/lib/grafana
    networks:
      - erpc_network
    depends_on:
      - erpc

volumes:
  prometheus_data:
  grafana_data:

networks:
  erpc_network:
    driver: bridge
