providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
nixPkgs = ['...', 'python3', 'gcc']
onlyIncludeFiles = []

[phases.install]
cmds = [
    'npm install -g corepack@latest && corepack enable',
    'yarn install --mode=update-lockfile',
    'yarn install',
]
onlyIncludeFiles = [
    'package.json',
    '.yarnrc.yml',
    '.yarn',
    'apps/emails/quorum/package.json',
    'libs/ts/db/package.json',
    'libs/ts/emails/package.json',
]

[phases.build]
cmds = ['yarn build-email-quorum']
onlyIncludeFiles = ['apps/emails/quorum', 'libs/ts/db', 'libs/ts/emails']

[start]
cmd = 'yarn start-email-quorum'
runImage = 'node:22-bookworm'
onlyIncludeFiles = [
    'apps/emails/quorum',
    'libs/ts/db',
    'libs/ts/emails',
    'node_modules',
    'package.json',
    'yarn.lock',
    '.yarnrc.yml',
    '.yarn',
]
