providers = ['rust']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[start]
cmd = './target/release/proposals_producer'
runImage = 'ubuntu:latest'
onlyIncludeFiles = ['./target/release/proposals_producer']

[phases.build]
cmds = ['cargo build --release --package proposals_producer']

[phases.setup]
nixPkgs = ['binutils', 'gcc', '(rust-bin.stable.latest.default)']
