providers = ['rust']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[start]
cmd = './bin/proposals_consumer'
runImage = 'ubuntu:jammy'
onlyIncludeFiles = ['./bin/proposals_consumer']

[phases.build]
cmds = [
    'mkdir -p bin',
    'cargo build --release --package proposals_consumer --target x86_64-unknown-linux-gnu',
    'cp target/x86_64-unknown-linux-gnu/release/proposals_consumer bin',
]

[phases.setup]
nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["x86_64-unknown-linux-gnu"]; })',
]
