providers = ['rust']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["aarch64-unknown-linux-musl"]; })',
    'musl',
    'musl.dev',
]
onlyIncludeFiles = ['Cargo.toml', 'apps/detective', 'libs/rust']

[phases.build]
dependsOn = ['setup']
cmds = [
    'cargo build --release --package proposals-consumer --target aarch64-unknown-linux-musl',
]
onlyIncludeFiles = ['Cargo.toml', 'apps/detective', 'libs/rust']

[variables]
PROPOSALS_BIN = 'proposals-consumer'

[start]
cmd = './target/aarch64-unknown-linux-musl/release/proposals-consumer'
runImage = 'debian:latest'
onlyIncludeFiles = [
    './target/aarch64-unknown-linux-musl/release/proposals-consumer',
]
