buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1707782610'

[variables]
NIXPACKS_METADATA = 'rust'

[start]
cmd = './bin/proposals_consumer'
runImage = 'ubuntu:jammy'
onlyIncludeFiles = ['./bin/proposals_consumer']

[phases.build]
dependsOn = ['setup']
cmds = [
    'mkdir -p bin',
    'cargo build --release --package proposals_consumer --target x86_64-pc-linux-gnu',
    'cp target/x86_64-pc-linux-gnu/release/proposals_consumer bin',
]
cacheDirectories = ['/root/.cargo/git', '/root/.cargo/registry']

[phases.setup]
nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["x86_64-pc-linux-gnu"]; })',
    'musl',
    'musl.dev',
]
nixOverlays = ['https://github.com/oxalica/rust-overlay/archive/master.tar.gz']
nixpkgsArchive = '5148520bfab61f99fd25fb9ff7bfbb50dad3c9db'
