providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
nixPkgs = ['...', 'python3', 'gcc']
onlyIncludeFiles = []

[phases.install]
cmds = [
    'npm install -g corepack@latest && corepack enable',
    'yarn install --mode=update-lockfile',
    'yarn install',
]
onlyIncludeFiles = [
    'package.json',
    '.yarnrc.yml',
    '.yarn',
    'apps/push/timeend/package.json',
    'libs/ts/db/package.json',
]

[phases.build]
cmds = ['yarn build-push-timeend']
onlyIncludeFiles = ['apps/push/timeend', 'libs/ts/db']

[start]
cmd = 'yarn start-push-timeend'
runImage = 'node:22-bookworm'
onlyIncludeFiles = [
    'apps/push/timeend',
    'libs/ts/db',
    'node_modules',
    'package.json',
    'yarn.lock',
    '.yarnrc.yml',
    '.yarn',
]
