providers = ['rust']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.build]
cmds = ['cargo build --release --package snapshot-sanity']
onlyIncludeFiles = ['Cargo.toml', 'Cargo.lock', 'apps/detective', 'libs/rust']

[start]
cmd = './target/release/snapshot-sanity'
runImage = 'debian:latest'
onlyIncludeFiles = ['./target/release/snapshot-sanity']
