providers = ['rust']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[variables]
NIXPACKS_METADATA = 'rust'

[start]
cmd = './bin/snapshot_sanity'
runImage = 'ubuntu:jammy'
onlyIncludeFiles = ['./bin/snapshot_sanity']

[phases.build]
dependsOn = ['setup']
cmds = [
    'mkdir -p bin',
    'cargo build --release --package snapshot_sanity --target x86_64-unknown-linux-musl',
    'cp target/x86_64-unknown-linux-musl/release/snapshot_sanity bin',
]
cacheDirectories = ['/root/.cargo/git', '/root/.cargo/registry']

[phases.setup]
nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["x86_64-unknown-linux-musl"]; })',
    'musl',
    'musl.dev',
    'wget',
    'curl',
]


[phases.runtime]
nixPkgs = ['curl', 'wget']
