providers = ['rust']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[variables]
NIXPACKS_METADATA = 'rust'
BIN_NAME = 'votes-producer'

[phases.setup]
nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["x86_64-unknown-linux-musl"]; })',
    'musl',
    'musl.dev',
]

[phases.build]
dependsOn = ['setup']
cmds = [
    'mkdir -p bin',
    'cargo build --release --package $BIN_NAME --target x86_64-unknown-linux-musl',
    'cp target/x86_64-unknown-linux-musl/release/$BIN_NAME bin',
]
cacheDirectories = ['/root/.cargo/git', '/root/.cargo/registry']


[start]
cmd = './bin/$BIN_NAME'
runImage = 'debian:bullseye-slim'
onlyIncludeFiles = ['./bin/$BIN_NAME']
