providers = ['rust']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[variables]
NIXPACKS_METADATA = 'rust'

[phases.setup]
nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["x86_64-unknown-linux-musl"]; })',
    'musl',
    'musl.dev',
]

[phases.build]
dependsOn = ['setup']
cmds = [
    'mkdir -p bin',
    'cargo build --release --package votes-producer --target x86_64-unknown-linux-musl',
    'cp target/x86_64-unknown-linux-musl/release/votes-producer bin',
]
cacheDirectories = ['/root/.cargo/git', '/root/.cargo/registry']


[start]
cmd = './bin/votes-producerE'
runImage = 'debian:bullseye-slim'
onlyIncludeFiles = ['./bin/votes-producer']
