providers = ['rust']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["x86_64-unknown-linux-musl"]; })',
    'musl',
    'musl.dev',
]

[phases.build]
dependsOn = ['setup']
cmds = [
    'mkdir -p bin',
    'cargo build --release --package votes-consumer --target x86_64-unknown-linux-musl',
    'cp target/x86_64-unknown-linux-musl/release/votes-consumer bin',
]
cacheDirectories = ['/root/.cargo/git', '/root/.cargo/registry']

[start]
cmd = './bin/votes-consumer'
runImage = 'debian:latest'
onlyIncludeFiles = ['./bin/votes-consumer']
