providers = ['rust']

buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[variables]
NIXPACKS_METADATA = 'rust'

[start]
cmds = [
    'apt-get update && apt-get install -y curl wget',
    './bin/votes_consumer',
]
runImage = 'ubuntu:jammy'
onlyIncludeFiles = ['./bin/votes_consumer']

[phases.build]
dependsOn = ['setup']
cmds = [
    'apt-get update && apt-get install -y curl wget',
    'mkdir -p bin',
    'cargo build --release --package votes_consumer --target x86_64-unknown-linux-musl',
    'cp target/x86_64-unknown-linux-musl/release/votes_consumer bin',
]
cacheDirectories = ['/root/.cargo/git', '/root/.cargo/registry']

nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["x86_64-unknown-linux-musl"]; })',
    'musl',
    'musl.dev',
    'wget',
    'curl',
]
