providers = ['rust']
buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[variables]
NIXPACKS_METADATA = 'rust'

[start]
cmd = './bin/votes_consumer'
runImage = 'ubuntu:jammy'
onlyIncludeFiles = ['./bin/votes_consumer']

[phases.build]
dependsOn = ['setup']
cmds = [
    'mkdir -p bin',
    'cargo build --release --package votes_consumer --target x86_64-pc-linux-gnu',
    'cp target/x86_64-pc-linux-gnu/release/votes_consumer bin',
]
cacheDirectories = ['/root/.cargo/git', '/root/.cargo/registry']

[phases.setup]
nixPkgs = [
    'binutils',
    'gcc',
    '(rust-bin.stable.latest.default.override { targets = ["x86_64-pc-linux-gnu"]; })',
    'musl',
    'musl.dev',
]
