---
- name: Setup Consul KV values for email-service in all datacenters
  hosts: consul_servers
  become: true
  vars:
    consul_kv_values:
      # BetterStack monitoring
      - key: "email-service/betterstack_key"
        value: "{{ vault_email_service_betterstack_key }}"

      # Email service configuration
      - key: "email-service/resend_api_key"
        value: "{{ vault_email_service_resend_api_key }}"

      # Application URL
      - key: "email-service/web_url"
        value: "{{ vault_email_service_web_url }}"

  tasks:
    - name: Ensure Consul is available
      wait_for:
        port: 8500
        host: localhost
        timeout: 60

    - name: Get local Consul datacenter info
      uri:
        url: "http://localhost:8500/v1/agent/self"
        method: GET
      register: consul_info

    - name: Set datacenter variable
      set_fact:
        current_datacenter: "{{ consul_info.json.Config.Datacenter }}"

    - name: Store values in local datacenter's Consul KV
      uri:
        url: "http://localhost:8500/v1/kv/{{ item.key }}"
        method: PUT
        body: "{{ item.value }}"
      loop: "{{ consul_kv_values }}"
      loop_control:
        label: "{{ item.key }} in {{ current_datacenter }}"
      no_log: true # Don't log sensitive values

    - name: Display setup information for this datacenter
      debug:
        msg: |
          ========================================
          Consul KV Setup Complete for {{ current_datacenter }}
          ========================================

          Environment variables have been stored in Consul KV
          for datacenter: {{ current_datacenter }}

          Run this playbook on all consul servers to replicate
          the configuration across all datacenters.
          ========================================
      run_once: true

- name: Display final deployment instructions
  hosts: localhost
  connection: local
  tasks:
    - name: Show deployment instructions
      debug:
        msg: |
          ========================================
          Email Service Setup Complete
          ========================================

          To deploy the email service:
          1. Ensure this playbook has been run on all consul servers
          2. Run: nomad job run infrastructure/ansible/applications/email-service/email-service.nomad

          The email service always deploys from the main branch.
          Feature branches are built and stored in ghcr.io but not automatically deployed.

          To verify the values in each datacenter:
          - consul kv get email-service/resend_api_key
          - consul kv get email-service/betterstack_key
          - consul kv get email-service/web_url
          - consul kv get pgpool/connection_string/local

          The email service will:
          - Run a single instance in any available datacenter
          - Automatically migrate between datacenters if needed
          - Connect to the local pgpool instance using the connection string from Consul KV
          - Send email notifications via Resend API
          - Report health to BetterStack for monitoring
          - Pull the latest Docker image from the main branch

          Service details:
          - Internal port: 3001
          - Health check endpoint: /health
          - Memory: 512MB (can burst to 768MB)
          - CPU: 0.5 cores
          - Logs: JSON format with 10MB rotation

          The service handles:
          - Sending proposal notification emails
          - User preference management
          - Email delivery tracking
          - Queue processing for scheduled emails

          Note: Database credentials are securely stored in Consul KV by the pgpool playbook
          ========================================