---
- name: Setup Consul KV values for email-service in all datacenters
  hosts: consul_servers
  become: true
  vars:
    consul_kv_values:
      # BetterStack monitoring
      - key: "email-service/betterstack_key"
        value: "{{ vault_email_service_betterstack_key }}"

      # Email service configuration
      - key: "email-service/resend_api_key"
        value: "{{ vault_email_service_resend_api_key }}"

  tasks:
    - name: Ensure Consul is available
      wait_for:
        port: 8500
        host: localhost
        timeout: 60

    - name: Get local Consul datacenter info
      uri:
        url: "http://localhost:8500/v1/agent/self"
        method: GET
      register: consul_info

    - name: Set datacenter variable
      set_fact:
        current_datacenter: "{{ consul_info.json.Config.Datacenter }}"

    - name: Store values in local datacenter's Consul KV
      uri:
        url: "http://localhost:8500/v1/kv/{{ item.key }}"
        method: PUT
        body: "{{ item.value }}"
      loop: "{{ consul_kv_values }}"
      loop_control:
        label: "{{ item.key }} in {{ current_datacenter }}"
      no_log: true # Don't log sensitive values

    - name: Display setup completion
      debug:
        msg: "Consul KV setup complete for email-service in {{ current_datacenter }}"
      run_once: true