global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
  - job_name: "tempo-metrics"
    static_configs:
      - targets: ["tempo:3200"]
  - job_name: "arbitrum-proposals-app"
    scheme: https
    static_configs:
      - targets: ["arbitrum.proposals.app"]
    metrics_path: /api/metrics # Specify the metrics path
    tls_config:
      insecure_skip_verify: true # Skip TLS verification if using self-signed certificates

  - job_name: "postgres"
    static_configs:
      - targets: 
        - "postgres-exporter-main:9187"
        - "postgres-exporter-web:9187"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: $1
        regex: '([^:]+)'
