export const BONEYARD_NAMES = {
  arbitrumSummaryHeader: 'arbitrum-summary-header',
  uniswapSummaryHeader: 'uniswap-summary-header',
  groupsHeader: 'groups-header',
  mainPage: 'main-page',
  groupList: 'group-list',
  groupPage: 'group-page',
  resultsPage: 'results-page',
  resultsContent: 'results-content',
  bodyHeader: 'body-header',
  body: 'body',
  menuBarFull: 'menu-bar-full',
  menuBarBody: 'menu-bar-body',
  menuBarComments: 'menu-bar-comments',
  initiallyPosted: 'initially-posted',
  postedRevisions: 'posted-revisions',
  activeGroupItem: 'active-group-item',
  inactiveGroupItem: 'inactive-group-item',
  discussionGroupItem: 'discussion-group-item',
  feed: 'feed',
  postItem: 'post-item',
  voteItemFeed: 'vote-item-feed',
  aggregateVoteItem: 'aggregate-vote-item',
  resultsHeader: 'results-header',
  resultsTitle: 'results-title',
  resultsList: 'results-list',
  resultsListBars: 'results-list-bars',
  resultsTable: 'results-table',
  nonVotersTable: 'non-voters-table',
  timeline: 'timeline',
  chart: 'chart',
  navShell: 'nav-shell',
  modeToggle: 'mode-toggle',
  profilePage: 'profile-page',
  onboardingPage: 'onboarding-page',
  mappingPage: 'mapping-page',
  delegatesPage: 'delegates-page',
} as const;

export type BoneyardName =
  (typeof BONEYARD_NAMES)[keyof typeof BONEYARD_NAMES];
