name: Node.js Tests

on:
  pull_request:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Node.js Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Corepack
        run: corepack enable && corepack prepare yarn@4 --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: |
          cd apps/email-service
          yarn test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: node-tests
          name: codecov-node
          verbose: true
